# Generated by Django 4.2.4 on 2023-08-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='to_photo',
            new_name='to_suit',
        ),
    ]
