# Generated by Django 4.2.4 on 2023-08-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_to_photo_comment_to_suit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
