# Generated by Django 4.2.4 on 2023-08-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0008_delete_size'),
        ('common', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('to_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suits.suit')),
            ],
        ),
    ]
