# Generated by Django 4.2.4 on 2023-08-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
