# Generated by Django 4.2.4 on 2023-08-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='to_shoe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes'),
            preserve_default=False,
        ),
    ]
