# Generated by Django 4.2.4 on 2023-08-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0003_alter_suit_personal_photo'),
        ('shoes', '0005_size_to_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='to_suit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suits.suit'),
            preserve_default=False,
        ),
    ]
