# Generated by Django 4.2.4 on 2023-08-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_size_to_suit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='to_suit',
        ),
    ]
