# Generated by Django 4.2.4 on 2023-08-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_remove_size_to_suit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='to_shoe',
            new_name='to_shoes',
        ),
    ]
