# Generated by Django 4.2.4 on 2023-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suit',
            name='personal_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='suit',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
