# Generated by Django 4.2.4 on 2023-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0002_alter_suit_personal_photo_alter_suit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suit',
            name='personal_photo',
            field=models.URLField(),
        ),
    ]
