# Generated by Django 4.2.4 on 2023-08-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0003_alter_suit_personal_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField()),
                ('to_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suits.suit')),
            ],
        ),
    ]
