# Generated by Django 4.2.4 on 2023-08-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0005_alter_size_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='to_suit',
            new_name='to_suits',
        ),
    ]
