# Generated by Django 4.2.4 on 2023-08-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0006_rename_to_suit_size_to_suits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='to_suits',
            new_name='to_suit',
        ),
    ]
