# Generated by Django 4.2.4 on 2023-08-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suits', '0007_rename_to_suits_size_to_suit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
